id: P009379
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS18910
  title: ཁོར་ཡུག་སྦགས་བཙོག་དང་སྲུང་སྐྱོབ་ཀྱི་སྐོར།
  author: ''
  volumes:
    21dc12d6d22e41b3b39c223ef1a72ab1:
      image_group_id: I8LS18912
      title: ''
      volume_number: 1
      total_pages: 328
      base_file: v001.txt
