id: P009379
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18910
  title: ཁོར་ཡུག་སྦགས་བཙོག་དང་སྲུང་སྐྱོབ་ཀྱི་སྐོར།
  author: ''
  volumes:
    21dc12d6d22e41b3b39c223ef1a72ab1:
      image_group_id: I8LS18912
      title: ''
      volume_number: 1
      total_pages: 328
